.\" Manpage for myMPD.
.\" Contact mail@jcgames.de to correct errors or typos.
.TH man 1 "24 May 2018" "1.0.0" "myMPD man page"
.SH NAME
myMPD \- Standalone MPD Web GUI written in C, utilizing Websockets and Bootstrap/JS
.SH SYNOPSIS
mympd [OPTION]...
.SH DESCRIPTION
myMPD is a lightweight MPD web client that runs without a dedicated webserver or interpreter. 
It's tuned for minimal resource usage and requires only very litte dependencies. 
myMPD is a fork of ympd.

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-host HOST\fR
connect to mpd at host, defaults to localhost
.TP
\fB\-p\fR, \fB\-\-port PORT\fR
connect to mpd at port, defaults to 6600
.TP
\fB\-D\fR, \fB\-\-digest HTDIGEST\fR	
path to htdigest file for authorization
.TP
\fB\-l\fR, \fB\-\-localport PORT\fR
skip authorization for local port
.TP
\fB\-w\fR, \fB\-\-webport PORT\fR
specifies the port for the webserver to listen to, defaults to 8080
.TP
\fB-s\fR, \fB\-\-streamport PORT
connect to mpd http stream at port [8000]
.TP
\fB\-u\fR, \fB\-\-user USERNAME\fR
drop privileges to the provided username after socket binding
.TP
\fB\-m\fR, \fB\-\-mpdpass PASSWORD\fR
specifies the password to use when connecting to mpd
.TP
\fB-i\fR, \fB\-\-coverimage FILENAME\fR
filename for coverimage [folder.jpg]
.TP
\fB\-V\fR, \fB\-\-version\fR
print version and exit
.TP
\fB\-\-help\fR
print all valid options and exits
.SH BUGS
No known bugs.
.SH AUTHOR
Juergen Mang (mail@jcgames.de)

https://github.com/jcorporation/ympd