.\" Manpage for mympd-script.
.\" Contact <mail@jcgames.de> to correct errors or typos.
.TH man 1 "02 Nov 2024" "19.0.0" "mympd-script man page"

.SH NAME
mympd-script \- mympd command line tool to execute scripts

.SH SYNOPSIS
mympd-script <uri> <partition> <scriptname> [arguments]

.SH DESCRIPTION
mympd-script is a small commandline tool to execute myMPD scripts.

.SH OPTIONS
.TP
\fBuri\fR
myMPD listening uri, e.g. "https://localhost"
.TP
\fBpartition\fR
MPD partition, e.g. "default"
.TP
\fBscriptname\fR
script to execute, use "-" to read the script from stdin.
.TP
\fBarguments\fR
optional space separated key=value pairs to fill the arguments table in the Lua script.

.SH AUTHOR
Juergen Mang (mail@jcgames.de)

.SH BUGS
If you find a bug, please report it at https://github.com/jcorporation/myMPD/issues

.SH SEE ALSO
https://github.com/jcorporation/myMPD
