.\" Manpage for mympd-config.
.\" Contact <mail@jcgames.de> to correct errors or typos.
.TH man 1 "12 Aug 2024" "17.0.1" "mympd-config man page"

.SH NAME
mympd-config \- mympd configuration tool

.SH SYNOPSIS
mympd-config [-b </usr/bin/mympd>] [-c </var/lib/mympd/config>] [-s <0|1>] [SETTING VALUE ...]

.SH DESCRIPTION
mympd-config is a small commandline tool to configure basic myMPD settings.

.SH OPTIONS
.TP
\fB-b <//usr/bin/mympd>\fR
Set's the path to the myMPD executable.
.TP
\fB-c </var/lib/mympd/config>\fR
Set's the path to the myMPD config directory.
.TP
\fB-s <0|1>\fR
0 = myMPD runs with normal linux user account
1 = myMPD ist started with systemd private user
.TP
\fBSETTING VALUE\fR
Valid settings are the environment variables respected by "mympd -c".

Reference: https://jcorporation.github.io/myMPD/configuration/configuration-files

.SH AUTHOR
Juergen Mang (mail@jcgames.de)

.SH BUGS
If you find a bug, please report it at https://github.com/jcorporation/myMPD/issues

.SH SEE ALSO
https://github.com/jcorporation/myMPD
