.\" Manpage for mympd-config.
.\" Contact <mail@jcgames.de> to correct errors or typos.
.TH man 1 "19 Mar 2021" "7.0.0" "mympd-config man page"
.SH NAME
mympd-config \- configuration tool for myMPD
.SH SYNOPSIS
mympd [/path/to/mympd.conf]
.SH DESCRIPTION
myMPD is a standalone and lightweight web-based MPD client. 

The command line tool mympd-config parses the MPD configuration file and configures myMPD accordingly. The tool sets sane and secure default options. If MPD and myMPD are installed in default locations there is no need to specify any path.
.SH OPTIONS
Look at https://github.com/jcorporation/myMPD/wiki/mympd-config
.SH BUGS
Look at https://github.com/jcorporation/myMPD/issues
.SH AUTHOR
Juergen Mang (mail@jcgames.de)

https://github.com/jcorporation/myMPD
