#
# SPDX-License-Identifier: GPL-3.0-or-later
# myMPD (c) 2018-2024 Juergen Mang <mail@jcgames.de>
# https://github.com/jcorporation/mympd
#
FROM alpine:latest
COPY . /myMPD/
WORKDIR /myMPD
RUN ./build.sh installdeps
RUN ./build.sh debug
RUN ./build.sh addmympduser

ENV MPD_HOST=127.0.0.1
ENV MPD_PORT=6600
ENTRYPOINT ["/myMPD/debug/mympd"]
