#!/bin/sh

if [ -f /usr/lib/systemd/system/mympd.service ]
then
  if `systemctl is-active --quiet mympd`
  then
    echo "Stopping mympd.service" && systemctl stop mympd 
  fi
  echo "Disabling mympd.service" && systemctl disable mympd
fi

if [ "$1" == "purge" ]
then
  if [ -f /usr/lib/systemd/system/mympd.service ]
  then
    rm /usr/lib/systemd/system/mympd.service
    systemctl daemon-reload
  fi
  rm -rf /usr/share/mympd
  rm -rf /etc/mympd
  rm -rf /var/lib/mympd
  userdel mympd
  groupdel mympd
fi
