name: test
on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: installdeps
      run: sudo ./build.sh installdeps
    - name: build
      run: |
        if ! ./build.sh test
        then
          debug/bin/unit_test
        fi
