name: lint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: install linters
      run: |
        sudo apt-get update
        sudo apt-get install -y npm clang-tidy lua-check
        sudo ./build.sh installdeps
        npm install eslint --save-dev
        npm install stylelint --save-dev
        npm install stylelint-config-standard --save-dev
        npm install htmlhint --save-dev
        npm install typescript --save-dev
        npm install eslint-plugin-jsdoc --save-dev
        npm install markdownlint-cli --save-dev
    - name: lint js css html lua
      run: ./build.sh lint
    - name: build debug and lint
      run: |
        ./build.sh debug
        ./build.sh check
